### ISSUE TITLE
[feature request] search through content

### ISSUE THREAD

**Issue by ulugbekna** [ocaml-explore/explore#58]
Hi! :-) 

It'd be nice to be able to searc through the website content.

**Comment by patricoferris** [comment]
Thanks for the suggestion -- you're [not the first](https://github.com/ocaml-explore/explore/issues/41) and I think it would be helpful ;) 

I think for now Explore OCaml will focus on the content and seeing as hopefully it will move to ocaml.org, tracking Gargi's comment [here](https://github.com/ocaml/ocaml.org/issues/1174#issuecomment-700045440) is probably the most sensible option.

**Comment by ulugbekna** [comment]
woops, I searched through open issues for "search" but didn't find anything. Sorry for the noise :)
